# Generated by Django 3.1.2 on 2020-10-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='Project', max_length=75),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.CharField(max_length=400),
        ),
    ]
